// Copyright (C) 2026 intnsity
// SPDX-License-Identifier: GPL-3.0-or-later

//! SeedSigner's published SeedQR test vectors, run against the ingress validator.
//!
//! Source: the SeedQR format specification's "Test SeedQRs - Sample test vectors to verify
//! your own encode and decode implementations" section,
//! <https://github.com/SeedSigner/seedsigner/blob/dev/docs/seed_qr/README.md>. All nine
//! are here, in both formats, unmodified. Nothing in this file was generated by this
//! project; where a value had to be re-expressed (the specification prints the
//! CompactSeedQR payload as a bit string and again as a Python bytes literal, and this
//! file uses hex) the re-expression is proven rather than trusted - see
//! `the_published_fields_of_each_vector_agree`, which recomputes the entropy from the
//! published digit stream with the specification's own rule and compares it to the
//! published payload. A transcription slip in either column fails that test.
//!
//! Vectors 2 and 6 carry an embedded `0x00`, 7 a `0x0a`, 8 a `0x0d`, 9 a `0x0d 0x0a`, and
//! vector 1 ENDS in `0x0a` - the specification chose them for exactly that reason ("Take
//! extra care to confirm that your implementation correctly reads these characters and
//! all remaining data after it!"). They are the reason this crate's decoder takes `&[u8]`
//! and trims nothing.

use notyas_core::bip39::{self, Checksum};
use notyas_core::seedqr::{self, Format, IngressError};

/// One published vector, in the three forms the specification prints it in.
struct Vector {
    /// The vector's number in the specification, so a failure names the row upstream.
    number: u32,
    mnemonic: &'static str,
    /// "Standard SeedQR digit stream" verbatim.
    digits: &'static str,
    /// "CompactSeedQR bytestream" as hex. The specification gives this as a Python bytes
    /// literal and as a bit string; both are the same value, and this file's transcription
    /// is checked against the digit stream column below.
    entropy_hex: &'static str,
}

const VECTORS: [Vector; 9] = [
    Vector {
        number: 1,
        mnemonic: "attack pizza motion avocado network gather crop fresh patrol unusual wild \
                   holiday candy pony ranch winter theme error hybrid van cereal salon goddess \
                   expire",
        digits: "011513251154012711900771041507421289190620080870026613431420201617920614089619290300152408010643",
        entropy_hex: "0e74b64107f94cc0ccfae6a13dcbec3662154fec67e0e00999c07892597d190a",
    },
    Vector {
        number: 2,
        mnemonic: "atom solve joy ugly ankle message setup typical bean era cactus various odor \
                   refuse element afraid meadow quick medal plate wisdom swap noble shallow",
        digits: "011416550964188800731119157218870156061002561932122514430573003611011405110613292018175411971576",
        entropy_hex: "0e59dde276009317f1275f1389888078c99368d1e82489b5f629531fc5b6a56e",
    },
    Vector {
        number: 3,
        mnemonic: "sound federal bonus bleak light raise false engage round stock update render \
                   quote truck quality fringe palace foot recipe labor glow tortoise potato still",
        digits: "166206750203018810361417065805941507171219081456140818651401074412730727143709940798183613501710",
        entropy_hex: "cfca8c658bc81962549252bc7ac3ba5b0b01d26bcae89f2b5ecebe263dcb2a36",
    },
    Vector {
        number: 4,
        mnemonic: "forum undo fragile fade shy sign arrest garment culture tube off merit",
        digits: "073318950739065415961602009907670428187212261116",
        entropy_hex: "5bbd9d71a8ec7990831aff359d426545",
    },
    Vector {
        number: 5,
        mnemonic: "good battle boil exact add seed angle hurry success glad carbon whisper",
        digits: "080301540200062600251559007008931730078802752004",
        entropy_hex: "6462686427203385c2337dd84c5089fd",
    },
    Vector {
        number: 6,
        mnemonic: "approve fruit lens brass ring actual stool coin doll boss strong rate",
        digits: "008607501025021714880023171503630517020917211425",
        entropy_hex: "0acbba008d9ba005f5996b40a3475cd9",
    },
    Vector {
        number: 7,
        mnemonic: "dignity utility vacant shiver thought canoe feel multiply item youth actor \
                   coyote",
        digits: "049619221923158517990268067811630950204300210397",
        entropy_hex: "3e1e0bc1e31e0e4315348b76dfec0a98",
    },
    Vector {
        number: 8,
        mnemonic: "corn voice scrap arrow original diamond trial property benefit choose junk lock",
        digits: "038719631547010112530489185713790169032209701051",
        entropy_hex: "307eaf058659ca7a7a0d63152509e541",
    },
    Vector {
        number: 9,
        mnemonic: "vocal tray giggle tool duck letter category pattern train magnet excite swamp",
        digits: "196218530783182905421028028912901848107106301753",
        entropy_hex: "f55cf587f2543d01090d0ae710bd3b6d",
    },
];

impl Vector {
    fn entropy(&self) -> Vec<u8> {
        hex::decode(self.entropy_hex).expect("vector entropy is hex")
    }

    fn words(&self) -> usize {
        self.mnemonic.split_whitespace().count()
    }
}

/// The CompactSeedQR payload recomputed from the Standard digit stream, by the
/// specification's rule and nothing else: "We know that the BIP-39 wordlist contains
/// exactly 2048 words. That means we will need 11 bits to express each index in binary",
/// "We concatenate all those binary values to one large 132-bit stream", then
/// "12-word CompactSeedQR = 132 bits - 4 checksum bits = 128 bits".
///
/// Written out here rather than called from the crate on purpose: this is the independent
/// witness that the two published columns in `VECTORS` were transcribed correctly, so it
/// must not share code with the thing under test.
fn compact_payload_from_digit_stream(digits: &str) -> Vec<u8> {
    let words = digits.len() / 4;
    let mut bits = String::new();
    for group in digits.as_bytes().chunks(4) {
        let index: u32 = std::str::from_utf8(group)
            .expect("digits are ASCII")
            .parse()
            .expect("four digits are a number");
        for shift in (0..11).rev() {
            bits.push(if (index >> shift) & 1 == 1 { '1' } else { '0' });
        }
    }
    // One checksum bit per three words, i.e. one per 32 entropy bits.
    bits.truncate(words * 11 - words / 3);
    bits.as_bytes()
        .chunks(8)
        .map(|byte| {
            byte.iter()
                .fold(0u8, |acc, &bit| (acc << 1) | u8::from(bit == b'1'))
        })
        .collect()
}

/// Before a single decode: are the vectors themselves self-consistent, and did they
/// survive being copied into this file?
///
/// This is the guard against the worst failure mode a vector suite has, which is a vector
/// quietly edited until the implementation agrees with it. The digit stream and the
/// CompactSeedQR payload are two independently published columns; if either one here
/// differs by a character from what SeedSigner printed, they stop agreeing.
#[test]
fn the_published_fields_of_each_vector_agree() {
    for vector in &VECTORS {
        let words = vector.words();
        assert!(
            words == 12 || words == 24,
            "vector {}: the specification publishes 12- and 24-word vectors only",
            vector.number
        );
        assert_eq!(
            vector.digits.len(),
            words * 4,
            "vector {}: four digits per word",
            vector.number
        );
        assert_eq!(
            compact_payload_from_digit_stream(vector.digits),
            vector.entropy(),
            "vector {}: the published digit stream and the published CompactSeedQR payload \
             are not the same seed. Do not adjust either value to make this pass - one of \
             them was mis-copied from the specification.",
            vector.number
        );
        // And the published mnemonic is a real BIP-39 phrase, which is what makes the
        // checksum assertions below meaningful.
        assert_eq!(
            bip39::check_phrase(vector.mnemonic).checksum,
            Checksum::Valid,
            "vector {}: the published mnemonic fails its own BIP-39 checksum",
            vector.number
        );
    }
}

#[test]
fn every_standard_vector_decodes() {
    for vector in &VECTORS {
        let scan = seedqr::decode(vector.digits.as_bytes())
            .unwrap_or_else(|e| panic!("vector {}: {e}", vector.number));
        assert_eq!(scan.format, Format::Standard, "vector {}", vector.number);
        assert_eq!(
            scan.mnemonic.phrase().as_str(),
            vector.mnemonic,
            "vector {}",
            vector.number
        );
        assert_eq!(scan.mnemonic.entropy, vector.entropy(), "vector {}", vector.number);
    }
}

#[test]
fn every_compact_vector_decodes() {
    for vector in &VECTORS {
        let scan = seedqr::decode(&vector.entropy())
            .unwrap_or_else(|e| panic!("vector {}: {e}", vector.number));
        assert_eq!(scan.format, Format::Compact, "vector {}", vector.number);
        assert_eq!(
            scan.mnemonic.phrase().as_str(),
            vector.mnemonic,
            "vector {}",
            vector.number
        );
        assert_eq!(scan.mnemonic.entropy, vector.entropy(), "vector {}", vector.number);
    }
}

/// The two formats of one seed must produce the identical phrase.
///
/// Stated separately from the two tests above because this is the property a user relies
/// on when they hold a Standard SeedQR in one hand and a CompactSeedQR of the same seed in
/// the other: the device must not care which one it read.
#[test]
fn the_two_formats_of_a_seed_agree() {
    for vector in &VECTORS {
        let standard = seedqr::decode(vector.digits.as_bytes()).expect("standard");
        let compact = seedqr::decode(&vector.entropy()).expect("compact");
        assert_eq!(
            standard.mnemonic.phrase().as_str(),
            compact.mnemonic.phrase().as_str(),
            "vector {}",
            vector.number
        );
        assert_ne!(standard.format, compact.format);
    }
}

/// No payload is classifiable as both formats, and the classifier agrees with the decoder.
///
/// The disjointness is structural - 16 and 32 against 48 and 96 - and this asserts it over
/// the whole length range rather than over the vectors, because it is the property that
/// makes format confusion impossible instead of merely unlikely. A future change that
/// admitted a 15-word Standard SeedQR (60 digits) would still pass; one that admitted a
/// 48-byte CompactSeedQR would not, and it is the one that silently changes a seed.
#[test]
fn no_payload_is_both_formats() {
    for len in 0..=256usize {
        // All-digit filler: the only payload that could be read as both, since a
        // non-digit payload can never be Standard.
        let payload = vec![b'7'; len];
        match seedqr::classify(&payload) {
            Some(Format::Compact) => assert!(len == 16 || len == 32, "len {len}"),
            Some(Format::Standard) => assert!(len == 48 || len == 96, "len {len}"),
            None => assert!(!seedqr::ACCEPTED_LENGTHS.contains(&len), "len {len}"),
        }
    }

    for vector in &VECTORS {
        assert_eq!(
            seedqr::classify(vector.digits.as_bytes()),
            Some(Format::Standard)
        );
        assert_eq!(seedqr::classify(&vector.entropy()), Some(Format::Compact));
    }
}

/// Vector 1's CompactSeedQR payload ends in `0x0a`. Trimming it is a different seed or no
/// seed at all, so nothing may trim it.
#[test]
fn a_trailing_newline_in_the_entropy_is_data() {
    let vector = &VECTORS[0];
    let entropy = vector.entropy();
    assert_eq!(
        entropy.last().copied(),
        Some(b'\n'),
        "vector 1's published payload is the one that ends in 0x0a; if this fails the \
         vector was mis-copied"
    );

    let scan = seedqr::decode(&entropy).expect("vector 1 decodes with its trailing 0x0a");
    assert_eq!(scan.mnemonic.phrase().as_str(), vector.mnemonic);

    // What a trim would have produced: 31 bytes, which is no format at all. The refusal is
    // the good case; the bad case would be a decoder that re-padded to 32 and produced a
    // valid mnemonic for a seed nobody owns.
    let trimmed = &entropy[..31];
    assert_eq!(
        seedqr::decode(trimmed).expect_err("31 bytes is not a SeedQR"),
        IngressError::UnknownLength { len: 31 }
    );
}

/// Every single-digit edit of every published Standard vector is either refused or a
/// different seed - never the original.
///
/// This is the property that makes the Standard format worth having: a transcription
/// error on a metal plate must not decode to the seed that was meant, and must not decode
/// to a plausible other seed without the checksum having had its say. The BIP-39 checksum
/// catches about 15 in 16; this asserts the remaining ones are at least visibly different
/// rather than silently the same.
#[test]
fn one_wrong_digit_never_yields_the_original_seed() {
    let mut accepted = 0usize;
    let mut refused = 0usize;
    for vector in &VECTORS {
        let original = vector.mnemonic;
        for position in 0..vector.digits.len() {
            for replacement in b'0'..=b'9' {
                let mut payload = vector.digits.as_bytes().to_vec();
                if payload[position] == replacement {
                    continue;
                }
                payload[position] = replacement;
                match seedqr::decode(&payload) {
                    Ok(scan) => {
                        accepted += 1;
                        assert_ne!(
                            scan.mnemonic.phrase().as_str(),
                            original,
                            "vector {}: digit {position} changed but the seed did not",
                            vector.number
                        );
                    }
                    Err(IngressError::ChecksumFailed { .. } | IngressError::IndexOutOfRange { .. }) => {
                        refused += 1;
                    }
                    Err(other) => panic!(
                        "vector {}: a one-digit edit should fail the checksum or the range, got {other:?}",
                        vector.number
                    ),
                }
            }
        }
    }
    // Printed, not pinned: the split depends on the vectors, and a pinned number would
    // fail for the wrong reason if a vector were added.
    println!("one-digit edits: {accepted} accepted as other seeds, {refused} refused");
    assert!(refused > accepted * 8, "the checksum should refuse the large majority");
}
