// Copyright (C) 2025-2026 intnsity
// SPDX-License-Identifier: GPL-3.0-or-later

//! Generates the compile-time BIP39 wordlist table.
//!
//! The desktop crate parses `wordlist_english.txt` at first use and caches the result in a
//! `std::sync::OnceLock`; this crate is no_std, so the parse moves to build time and the
//! cache becomes a plain `static`. The build also pins the file's identity: the embedded
//! list must be byte-for-byte the published upstream `bip-0039/english.txt`, and a copy
//! that drifted - a re-sorted line, a smuggled word, a CRLF rewrite by a checkout - fails
//! the build rather than deriving different wallets.

use std::env;
use std::fs;
use std::path::Path;

use sha2::{Digest, Sha256};

/// SHA-256 of bitcoin/bips `bip-0039/english.txt`, the same digest the desktop crate
/// documents beside its `include_str!`:
/// 2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda
const WORDLIST_SHA256: &str = "2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda";

/// Words in the BIP39 list. Must agree with `bip39::WORDLIST_LEN`, which the generated
/// code references by name so the two cannot drift silently.
const WORDLIST_LEN: usize = 2048;

fn main() {
    println!("cargo:rerun-if-changed=src/wordlist_english.txt");

    let bytes = fs::read("src/wordlist_english.txt").expect("wordlist_english.txt is missing");

    let digest = Sha256::digest(&bytes);
    let hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();
    assert_eq!(
        hex, WORDLIST_SHA256,
        "embedded BIP39 wordlist does not match the published upstream file \
         (check line endings: the file must keep its LF endings)"
    );

    let text = String::from_utf8(bytes).expect("wordlist is UTF-8");
    let words: Vec<&str> = text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect();
    // The same two structural checks the desktop crate makes at first use, moved to build
    // time: a wrong count or an unsorted list is a build defect, not a runtime condition.
    assert_eq!(
        words.len(),
        WORDLIST_LEN,
        "embedded BIP39 wordlist is corrupt"
    );
    assert!(
        words.windows(2).all(|w| w[0] < w[1]),
        "embedded BIP39 wordlist is not sorted"
    );

    let mut out = String::with_capacity(32 * 1024);
    out.push_str(
        "/// The official BIP39 English wordlist, generated by build.rs from\n\
         /// `src/wordlist_english.txt` (SHA-256 verified against the upstream digest).\n\
         static WORDLIST: [&str; WORDLIST_LEN] = [\n",
    );
    for word in &words {
        out.push_str("    \"");
        out.push_str(word);
        out.push_str("\",\n");
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    fs::write(Path::new(&out_dir).join("wordlist.rs"), out).expect("cannot write wordlist.rs");
}
