#!/usr/bin/env bash
# check-screenshots.sh - docs/screenshots/ui is a build output, and it must be
# the CURRENT one.
#
# tools/uisim drives notyas-ui through its public touch API and renders every
# screen to PNG. Those PNGs are committed: they are the UI review surface, they
# are what a reader of the README sees, and they are the only artifact of the UI
# that survives outside a running device. Two failures they are prone to, both
# silent:
#
#   1. Stale. A UI change lands, nobody re-runs the simulator, and the pictures
#      go on showing a screen that no longer exists.
#   2. Non-deterministic. Something in the render path (iteration order over a
#      hash map, an uninitialised buffer, a time or locale dependency) makes the
#      bytes differ run to run, which would make every future diff meaningless.
#
# Regenerating and demanding a byte-identical result catches both. The simulator
# already renders each frame twice and refuses to write on a mismatch, so it
# catches within-run nondeterminism itself; this catches the across-run and
# across-machine kind, and staleness.
#
# Usage:  tools/ci/check-screenshots.sh
#
# Run it from a clean working tree: it regenerates in place and diffs against the
# index, so uncommitted screenshot edits are reported as failures (correctly - an
# edited screenshot is exactly what must not be committed).
#
# Running it locally on a checkout that lives on a network share: set
# CARGO_TARGET_DIR to a short LOCAL path first (the repository convention, see
# firmware/README.md). CI runs on a local disk and needs nothing.

set -euo pipefail

cd "$(dirname "$0")/../.."

SHOTS=docs/screenshots/ui

echo "regenerating $SHOTS with tools/uisim ..."
cargo run --locked --quiet -p uisim

CHANGED=$(git status --porcelain -- "$SHOTS")

if [ -n "$CHANGED" ]; then
    echo
    echo "SCREENSHOT MISMATCH"
    echo
    printf '%s\n' "$CHANGED" | sed 's/^/  /'
    echo
    git --no-pager diff --stat -- "$SHOTS" | sed 's/^/  /'
    cat <<EOF

The committed screenshots are not what tools/uisim renders from this tree.

If you changed the UI, this is expected - regenerate and commit:
    cargo run -p uisim
    git add $SHOTS
    git commit

If you did NOT change the UI, this is a determinism failure, and it is the more
interesting outcome: the same code produced different bytes on this machine than
on the one that committed them. Look at the render path for anything that is not
a pure function of the state (iteration order, uninitialised memory, a float
path, a locale or time dependency) and at the PNG encoder settings, which are
pinned in tools/uisim (Paeth filter, best compression) precisely so the output
cannot drift.
EOF
    echo
    echo "check-screenshots: FAILED"
    exit 1
fi

echo "check-screenshots: OK - regenerated byte-identical to what is committed"
exit 0
